version: '3.9'
services:
    db:
        image: mongo
        container_name: ecommerce_db
        restart: always
        env_file:
            - .env
        ports:
            - '${DEV_MONGO_PORT}:${DEV_MONGO_PORT}'
        environment:
            MONGO_INITDB_ROOT_USERNAME: $DEV_MONGO_USERNAME
            MONGO_INITDB_ROOT_PASSWORD: $DEV_MONGO_PASSWORD
        volumes:
            - mongodb-data:/data/db
volumes:
    mongodb-data:
