version: '3.9'
services:
    db:
        image: mongo
        container_name: ecommerce_db
        restart: always
        env_file:
            - .env
        ports:
            - '${MONGO_PORT}:${MONGO_PORT}'
        environment:
            MONGO_INITDB_ROOT_USERNAME: $MONGO_USERNAME
            MONGO_INITDB_ROOT_PASSWORD: $MONGO_PASSWORD
